name: aiaprtd_member
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+2

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_auth: ^6.5.1
  cloud_firestore: ^6.4.1
  provider: ^6.1.5+1
  firebase_core: ^4.9.0
  audioplayers: ^6.6.0
  google_maps_flutter: ^2.17.0
  geolocator: ^14.0.2
  flutter_compass: ^0.8.1
  firebase_storage: ^13.4.5
  intl: ^0.20.3
  cached_network_image: ^3.4.1
  http: ^1.6.0
  image_picker: ^1.2.3
  camera: ^0.10.6
  google_mlkit_face_detection: ^0.13.2
  dash_bubble: ^2.0.0
  app_to_foreground: ^0.0.3
  local_auth: ^3.0.1
  geocoding: ^5.0.0
  url_launcher: ^6.3.2
  pdf: ^3.12.0
  path_provider: ^2.1.6
  shared_preferences: ^2.5.5
  flutter_local_notifications: ^22.0.1
  video_player: ^2.11.1
  google_fonts: ^8.1.0
  battery_plus: ^7.1.0
  record: ^7.1.1
  image: ^4.9.1
  mailer: ^7.1.0
  share_plus: ^13.2.0
  font_awesome_flutter: ^11.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true

  # 📌 ඇසෙට්ස් (Logo & Sound) ලියාපදිංචි කරපු කොටස
  assets:
    - assets/images/logo.png
    - assets/sounds/intro.mp3
    - assets/sounds/go_sound.mp3
    - assets/sounds/off_sound.mp3
    - assets/sounds/error_sound.mp3
    - assets/vehicles.json
    - assets/front.png
    - assets/back.png
    - assets/left_side.png
    - assets/right_side.png
    - assets/interior.png
    - assets/icons/app_icon.png # මේ පේළිය හැදුවා
    - assets/images/budget.png
    - assets/images/mini.png
    - assets/images/sedan.png
    - assets/images/6_seater.png
    - assets/images/9_seater.png
    - assets/images/14_seater.png
    - assets/images/map_budget.png
    - assets/images/map_mini.png
    - assets/images/map_sedan.png
    - assets/images/map_6_seater.png
    - assets/images/map_9_seater.png
    - assets/images/map_14_seater.png


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png" # උඹේ අලුත් ලෝගෝ එක තියෙන තැන
  min_sdk_android: 21

dependency_overrides:
  sqflite: 2.4.1
  sqflite_android: 2.4.1 # අර ටයිප් වෙලා තිබ්බ ප්‍රශ්නෙ අයින් කරා